config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/help", to: "static_pages#help"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resource :session, only: [:new, :create, :destroy]
  resources :activate_accounts, only: [:edit]
  resources :reset_passwords, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/controllers/reset_passwords_controller.rb
class ResetPasswordsController < ApplicationController

    def new
    end

    def create
        @user = User.find_by(email: params[:reset_password][:email])
        if @user
            @user.reset_password
            #user.update_attribute(:reset_digest, user.reset_digest)
            UsersMailer.reset_password(@user).deliver_now
            flash[:success] = "send a email"
            redirect_to root_path
        else
            flash.now[:danger] = "invalid email address"
            render "new", status: :unprocessable_entity
        end
    end

    def edit
        @user = User.find_by(email: params[:email])
        unless @user && @user.authenticated?(:reset, params[:id])
            flash[:danger] = "invalid email address"
            redirect_to root_path, status: :see_other
        end
    end

    def update
        @user = User.find_by(email: params[:email])
        if @user && @user.authenticated?(:reset, params[:id])
            if params[:user][:password].empty?                  # （3）への対応
                @user.errors.add(:password, "can't be empty")
                render 'edit', status: :unprocessable_entity
            elsif @user.update(user_params)                     # （4）への対応
                reset_session
                log_in @user, "0"
                flash[:success] = "Password has been reset."
                redirect_to @user
            else
                render 'edit', status: :unprocessable_entity      # （2）への対応
            end
        end
    end

    private
        def user_params
            params.require(:user).permit(:password, :password_confirmation)
        end
end

app/helpers/reset_passwords_helper.rb
module ResetPasswordsHelper
end

app/views/reset_passwords/edit.html.erb
<% provide(:title, "Reset password") %>
<%= form_with(model: @user, url: reset_password_url(params[:id])) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= hidden_field_tag :email, @user.email%>
  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>
  <%= f.submit "Reset password", class:"btn btn-primary" %>
<% end%>

app/views/reset_passwords/new.html.erb
<% provide(:totle, "To reset your password") %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>send a mail</h1>
    <%= form_with(url: reset_passwords_url, scope: :reset_password) do |f| %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      <%= f.submit "send a mail to reset password", class:"btn btn-primary" %>
    <% end %>
  </div>
</div>